# Generated by Django 3.0.5 on 2021-07-01 06:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_type', models.IntegerField(choices=[(1, 'CNY'), (2, 'USD')], default=1, verbose_name='货币类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='充值金额')),
                ('act_currency_type', models.IntegerField(choices=[(1, 'CNY'), (2, 'USD')], default=1, verbose_name='实际交易货币类型')),
                ('order_status', models.IntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '支付失败')], default=0, verbose_name='订单状态')),
                ('content', models.CharField(max_length=128, verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
